import Head from 'next/head'
import styles from './todo/Todo.module.css'
import TodoHome from './todo/TodoHome'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoHome />
    </div>
  )
}
